name: Sync from Gitee
on:
  schedule:
    - cron: "0 */6 * * *"  # 每6小时同步一次
  workflow_dispatch:       # 支持手动触发

jobs:
sync:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout GitHub Repo
      uses: actions/checkout@v4

    - name: Sync from Gitee
      run: |
        git remote add gitee git@gitee.com:你的用户名/仓库名.git
        git pull gitee main --rebase  # 以rebase方式拉取Gitee代码（避免冲突）
        git push origin main
